spring.data.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.authentication-database=${MONGO_AUTH_DB:admin} # Default to 'admin' if not set
openapi.swaggerOderstoreOpenAPI30.base-path:/
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error